[workspace]
resolver = "2"
version = "0.1.6"
authors = [
	"michaelangeloio"
]

members = [
    "crates/what-does-it-throw",
    "crates/what-does-it-throw-wasm"
]

exclude = [
    "docs/examples/quickstart/rust"
]

[profile.release]
debug = false

[profile.bench]
debug = true
