[workspace]
resolver = "2"

members = [
    "crates/does-it-throw",
    "crates/does-it-throw-wasm"
]

exclude = [
    "docs/examples/quickstart/rust"
]

[profile.release]
# Set this to true if you need to debug release builds
debug = false

[profile.bench]
debug = true
