name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      actions: read
      contents: write
      pull-requests: write
      issues: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - uses: oven-sh/setup-bun@a1800f471a0bc25cddac36bb13e6f436ddf341d7

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@0d096b08b4e5a7de8c28de67e11e945404e9eefa
        with:
          version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Create Release Pull Request or Publish to Vscode Marketplace
        uses: changesets/action@f13b1baaa620fde937751f5d2c3572b9da32af23
        with:
          title: Release Tracking
          publish: bun run release
          version: bun run version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
