on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install Bun
        uses: oven-sh/setup-bun@a1800f471a0bc25cddac36bb13e6f436ddf341d7

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@0d096b08b4e5a7de8c28de67e11e945404e9eefa
        with:
          version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest 

      - name: Publish to Visual Studio Marketplace
        if: ${{ steps.release.outputs.release_created }}
        uses: HaaLeo/publish-vscode-extension@65512ae7dcf96159b51fdd7ed73eb17d5cacad33
        with:
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
